name: Download artifacts

on:
  workflow_run:
    workflows: ["Upload artifacts"]
    types:
      - completed

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display structure of downloaded files
        run: ls

      - name: Decompress files
        run: |
          tar -xzf compressed-files/files.tar.gz

      - name: Display structure of downloaded files
        run: |
          ls -R