name: GitHub Actions Demo
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # temp-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        python-version: [ "3.7.10" ]
        torch-version: [ "1.10.0" ]
        cuda-version: [ "10.2.89" ]
    env:
      MY_ENV_VAR: ${{ matrix.python-version == '3.6' && 'value_for_main_branch' || 'value_for_other_branches' }}
    
    steps:
      - run: |
          echo "temp-version: --> ${{ matrix.temp-version }}"
          echo "python-version: --> ${{ matrix.python-version }}"
          echo "cuda-version: --> ${{ matrix.cuda-version }}"
          if [ "${{ matrix.cuda-version }}" = "" ]; then
            echo "empty"
            
          else
            echo "Task A"
          fi
          # echo "test $(if [ "${{ matrix.cuda-version }}" = "" ]; then "tttkkk" fi
          echo "? The job was automatically triggered by a ${{ github.event_name }} event."
          echo "? This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "? The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

          echo "MY_ENV_VAR: --> ${{ env.MY_ENV_VAR }}"

          if [ "${{ matrix.cuda-version }}" = "10.2.89" ]; then
            echo "good"
          else
            echo "bad"
          fi
        
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - run: echo "? The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "?️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "? This job's status is ${{ job.status }}."
      -
        name: Create a folder
        run: |
          mkdir -p sharedfolder

          touch sharedfolder/${{ matrix.temp-version }}_test1.sh
          touch sharedfolder/${{ matrix.temp-version }}_test2.sh

  # Upload_the_github:
  #   runs-on: ubuntu-latest
  #   needs: Explore-GitHub-Actions
  #   steps:
      - name: Upload the folder
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: sharedfolder # or path/to/artifact
